# Generated by Django 3.0.4 on 2020-05-18 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_auto_20200515_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cimages',
            old_name='food',
            new_name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('hediye', 'hediye'), ('etkinlik', 'etkinlik'), ('kampanya', 'kampanya')], max_length=10),
        ),
    ]
