# Generated by Django 3.0.4 on 2020-04-08 16:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200406_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
